[package]
name = "factorio"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
flate2 = "1.0.35"
json = "0.12.4"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
